### ISSUE TITLE
Chrome HTTPS not working

### ISSUE THREAD

**Issue by FinchMint** [brainfoolong/better-battlelog#3]
Hi, are you the one managing the plugin at Chrome web store (https://chrome.google.com/webstore/detail/better-battlelog-bblog/kjlfnjepjdmlppapoikepbaabbghofma)?

Battlelog started redirecting from HTTP to HTTPS version of the site. Any chance you could do a little modification to the permissions so that it also works on the HTTPS version (like the FireFox version)?

**Comment by brainfoolong** [comment]
Hi, yes i manage it. But it is end of life and development has been stopped, even for this tweak. Sorry.

**Comment by brainfoolong** [comment]
Hi @FinchMint . I've deviced to push out an update to support https. It's now live in chrome extension store. Greetz
