### ISSUE TITLE
Better BF Portal? 🤔

### ISSUE THREAD

**Issue by AdrianoCahete** [brainfoolong/better-battlelog#5]
**DID YOU KNOW WHAT WILL CAME BACK IN BF2042?**
No, not Battlelog... Sorry.

But the new "Builder Experience" for custom servers will be... **web-based**!

Ok, we don't even know how this will be, but it's a starter idea to get back again! :D

**Comment by brainfoolong** [comment]
Sounds interesting, maybe BBP (Better Battlefield Portal) is coming :)

**Comment by AdrianoCahete** [comment]
Aaaand I'm back.

EA releases a review portal page here: https://review.portal.battlefield.com/

Seems to be free to use even if you don't have the Battlefield 20142. I don't know if it will be like this after the release.

**Comment by brainfoolong** [comment]
Hi. I've played around a bit. Functionality isn't bad but unfortunately, as expected, it is only a game mode editor.
Currently i don't see a lot of potential for a new extension to improve this experience.
My personal opinion: Everyone will try this tool at the beginning, but it quickly will become uninteresting for the most players. Only server admins and modders will stick with this for long.

**Comment by AdrianoCahete** [comment]
Sadly, I Agree with you :(
