### ISSUE TITLE
This extension violates the Chrome Web Store policy.

### ISSUE THREAD

**Issue by WarlockZone** [brainfoolong/better-battlelog#7]
Hi devs. This is amazing extension, i still using it and playing BF3-4. Can you fix this?

**Comment by brainfoolong** [comment]
Unfortunately not in the chrome store. The extension is not compliant with the latest chrome extension rules and it would require a lot of rework, data policy, etc... to make it working again. Sorry. 

But maybe a workaround for you is to install the extension from source without the google store:

1. Download https://github.com/brainfoolong/better-battlelog/raw/master/versions/4.9.3/bblog.zip
2. Unpack to a folder you like
3. Open your Chrome -> Extensions -> Load unpacked extension and choose the folder of the unpacked zip file
4. Should now work again

![image](https://user-images.githubusercontent.com/1684236/181936491-06716375-7b74-45b7-a114-116d3d3404bd.png)

**Comment by WarlockZone** [comment]
Thank you for reply. It's works now, but until 2023 year( I saw it in Errors:
"Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details."

**Comment by brainfoolong** [comment]
Yep, but's that's another topic. Maybe i find time to upgrade to a new version with the new manifest, we'll see. For now, you can use it again :)

**Comment by WarlockZone** [comment]
Yeah, that would we awesome! Thank you again!
